import { loadRegistry } from "../core/registry.ts";
import type { Inventory } from "../core/types.ts";

export interface ScriptGenerationResult {
  script: string;
  included: string[];
  skipped: string[];
}

export async function generateScript(
  baseDir: string,
  actionName: string,
  ids: string[],
  current: Inventory,
): Promise<{ error?: string; result?: ScriptGenerationResult }> {
  const registry = await loadRegistry(baseDir);
  const action = registry.actions.find((a) => a.name === actionName);
  if (!action) {
    return { error: `unknown action: ${actionName}` };
  }

  const included: string[] = [];
  const skipped: string[] = [];
  const scriptLines: string[] = [];

  for (const id of ids) {
    const project = current.projects.find((p) => p.id === id);
    if (!project || !action.appliesTo(project)) {
      skipped.push(project?.relPath ?? id);
      continue;
    }
    included.push(project.relPath);
    scriptLines.push(...action.script(project, current.root));
  }

  const script = `#!/usr/bin/env bash
# Generated by repo-inventory on ${new Date().toISOString()}
# Action: ${action.label} — ${action.description}
# Projects: ${included.length}
#
# REVIEW EVERY LINE BEFORE RUNNING. This script is never executed by the tool.
set -euo pipefail

ROOT="${current.root}"

${scriptLines.join("\n")}
echo "done"
`;

  return { result: { script, included, skipped } };
}
